<?php
	define('FPDF_FONTPATH','./font/');
    define('CSRF', 'csrf_token');
    define('SIZE', 1140);
    define('DUE', 2);
    define('TRE', 3);
    define('CINQUE', 5);
    define('ZERO',0);
    define('DIECI',10);
    define('OTTO',8);
    define('QUATTRO',4);
    define('UNO',1);
    define('SEI',6);
    define('DODICI',12);
    define('MON','mon');
    define('MDAY','mday');
    define('YEAR','year');
    define('SETTE',7);
    define('NOVE',9);
    define('UNDICI',11);
    define('TREDICI',13);
    define('ARIAL','Arial');
    define('B','b');
    define('QUINDICI',15);
    define('OTTANTA',80);
    define('TRENTA',30);
    define('C','C');
    define('LOGO','Sensor Logic System');
    define('VENTI',20);
    define('MENOQUINDICI',-15);
    define('I','I');
    define('DUECENTO55',255);
    define('CENTO28',128);
    define('VUOTO','');
    define('PUNTOTRE',.3);
    define('VENTIQUATTRO',24);
    define('DUECENTO24',224);
    define('DUECENTO35',235);
    define('LR','LR');
    define('R','R');
    define('L','L');
    
    